// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXlpfZigW0ji328myx9nkX3XIteMY_DT0',
    appId: '1:973447115009:web:3e99ae21d5ea088ea42b00',
    messagingSenderId: '973447115009',
    projectId: 'employee-master-98d0d',
    authDomain: 'employee-master-98d0d.firebaseapp.com',
    storageBucket: 'employee-master-98d0d.firebasestorage.app',
    measurementId: 'G-HB5DTDBT8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7DJvFD8HV4BQAs77cYyx6Np-WPcg6zMw',
    appId: '1:973447115009:android:fd6df1deb6e7b91ba42b00',
    messagingSenderId: '973447115009',
    projectId: 'employee-master-98d0d',
    storageBucket: 'employee-master-98d0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqD57rM6ypcUYpl2RPNKW3HSPclWrAUpY',
    appId: '1:973447115009:ios:48ec49e0c7e23d44a42b00',
    messagingSenderId: '973447115009',
    projectId: 'employee-master-98d0d',
    storageBucket: 'employee-master-98d0d.firebasestorage.app',
    iosBundleId: 'com.example.employesMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqD57rM6ypcUYpl2RPNKW3HSPclWrAUpY',
    appId: '1:973447115009:ios:48ec49e0c7e23d44a42b00',
    messagingSenderId: '973447115009',
    projectId: 'employee-master-98d0d',
    storageBucket: 'employee-master-98d0d.firebasestorage.app',
    iosBundleId: 'com.example.employesMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXlpfZigW0ji328myx9nkX3XIteMY_DT0',
    appId: '1:973447115009:web:7ed3fecd560d2fcca42b00',
    messagingSenderId: '973447115009',
    projectId: 'employee-master-98d0d',
    authDomain: 'employee-master-98d0d.firebaseapp.com',
    storageBucket: 'employee-master-98d0d.firebasestorage.app',
    measurementId: 'G-K9MZ5DHWWY',
  );
}
